In [163]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
%matplotlib inline

In [164]:
df =pd.read_csv('/content/first inten project.csv')

In [165]:
df.head()

Booking_ID  number of adults  number of children  number of weekend nights  \
0   INN00001                 1                   1                         2   
1   INN00002                 1                   0                         1   
2   INN00003                 2                   1                         1   
3   INN00004                 1                   0                         0   
4   INN00005                 1                   0                         1   

   number of week nights  type of meal  car parking space    room type  \
0                      5   Meal Plan 1                  0  Room_Type 1   
1                      3  Not Selected                  0  Room_Type 1   
2                      3   Meal Plan 1                  0  Room_Type 1   
3                      2   Meal Plan 1                  0  Room_Type 1   
4                      2  Not Selected                  0  Room_Type 1   

   lead time market segment type  repeated  P-C  P-not-C  average price   \
0        224             Offline         0    0        0           88.00   
1          5              Online         0    0        0          106.68   
2          1              Online         0    0        0           50.00   
3        211              Online         0    0        0          100.00   
4         48              Online         0    0        0           77.00   

   special requests date of reservation booking status  
0                 0           10/2/2015   Not_Canceled  
1                 1           11/6/2018   Not_Canceled  
2                 0           2/28/2018       Canceled  
3                 1           5/20/2017       Canceled  
4                 0           4/11/2018       Canceled

In [166]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36285 entries, 0 to 36284
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Booking_ID                36285 non-null  object 
 1   number of adults          36285 non-null  int64  
 2   number of children        36285 non-null  int64  
 3   number of weekend nights  36285 non-null  int64  
 4   number of week nights     36285 non-null  int64  
 5   type of meal              36285 non-null  object 
 6   car parking space         36285 non-null  int64  
 7   room type                 36285 non-null  object 
 8   lead time                 36285 non-null  int64  
 9   market segment type       36285 non-null  object 
 10  repeated                  36285 non-null  int64  
 11  P-C                       36285 non-null  int64  
 12  P-not-C                   36285 non-null  int64  
 13  average price             36285 non-null  float64
 14  specia

In [167]:
# Convert date and extract features
df['date of reservation'] = pd.to_datetime(df['date of reservation'],errors='coerce')
df['year of reservation'] = df['date of reservation'].dt.year
df['month of reservation'] = df['date of reservation'].dt.month
df['day of reservation'] = df['date of reservation'].dt.day

In [168]:
df.head()

Booking_ID  number of adults  number of children  number of weekend nights  \
0   INN00001                 1                   1                         2   
1   INN00002                 1                   0                         1   
2   INN00003                 2                   1                         1   
3   INN00004                 1                   0                         0   
4   INN00005                 1                   0                         1   

   number of week nights  type of meal  car parking space    room type  \
0                      5   Meal Plan 1                  0  Room_Type 1   
1                      3  Not Selected                  0  Room_Type 1   
2                      3   Meal Plan 1                  0  Room_Type 1   
3                      2   Meal Plan 1                  0  Room_Type 1   
4                      2  Not Selected                  0  Room_Type 1   

   lead time market segment type  repeated  P-C  P-not-C  average price   \
0        224             Offline         0    0        0           88.00   
1          5              Online         0    0        0          106.68   
2          1              Online         0    0        0           50.00   
3        211              Online         0    0        0          100.00   
4         48              Online         0    0        0           77.00   

   special requests date of reservation booking status  year of reservation  \
0                 0          2015-10-02   Not_Canceled               2015.0   
1                 1          2018-11-06   Not_Canceled               2018.0   
2                 0          2018-02-28       Canceled               2018.0   
3                 1          2017-05-20       Canceled               2017.0   
4                 0          2018-04-11       Canceled               2018.0   

   month of reservation  day of reservation  
0                  10.0                 2.0  
1                  11.0                 6.0  
2                   2.0                28.0  
3                   5.0                20.0  
4                   4.0                11.0

In [169]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36285 entries, 0 to 36284
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype         
---  ------                    --------------  -----         
 0   Booking_ID                36285 non-null  object        
 1   number of adults          36285 non-null  int64         
 2   number of children        36285 non-null  int64         
 3   number of weekend nights  36285 non-null  int64         
 4   number of week nights     36285 non-null  int64         
 5   type of meal              36285 non-null  object        
 6   car parking space         36285 non-null  int64         
 7   room type                 36285 non-null  object        
 8   lead time                 36285 non-null  int64         
 9   market segment type       36285 non-null  object        
 10  repeated                  36285 non-null  int64         
 11  P-C                       36285 non-null  int64         
 12  P-not-C           

In [170]:

# Handle outliers (capping at 1st and 99th percentile)
numeric_cols = df.select_dtypes(include=np.number).columns
for col in numeric_cols:
    lower_bound = df[col].quantile(0.01)
    upper_bound = df[col].quantile(0.99)
    df[col] = df[col].clip(lower=lower_bound, upper=upper_bound)


In [171]:
# Import label encoder
from sklearn import preprocessing

# label_encoder object knows
# how to understand word labels.
label_encoder = preprocessing.LabelEncoder()

# Encode labels in column 'species'.
df['type of meal']= label_encoder.fit_transform(df['type of meal'])
df['market segment type']= label_encoder.fit_transform(df['market segment type'])
df['room type']= label_encoder.fit_transform(df['room type'])
df['booking status']= label_encoder.fit_transform(df['booking status'])
df['type of meal'].unique()

array([0, 3, 1, 2])

In [172]:
df['market segment type'].unique()

array([3, 4, 2, 0, 1])

In [173]:
df['room type'].unique()

array([0, 3, 1, 5, 4, 6, 2])

In [174]:
df.drop(['Booking_ID', 'P-C', 'P-not-C','date of reservation'], axis=1, inplace=True)

In [175]:
from sklearn.model_selection import train_test_split

In [176]:
# 5. Train-Test Split
X = df.drop('booking status', axis=1)
y = df['booking status']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [177]:

import xgboost as xgb
from sklearn.metrics import accuracy_score

# Initialize and train the XGBoost model
xgb_model = xgb.XGBClassifier(random_state=42)  # You can tune hyperparameters here
xgb_model.fit(X,y)

# Make predictions on the test set
y_pred_xgb = xgb_model.predict(X)

# Evaluate the model
accuracy_xgb = accuracy_score(y, y_pred_xgb)
print(f"XGBoost Accuracy: {accuracy_xgb}")


XGBoost Accuracy: 0.9180928758440127


In [178]:

# Initialize and train the Random Forest Classifier
rf_model = RandomForestClassifier(random_state=42)  # You can tune hyperparameters here
rf_model.fit(X,y)

# Make predictions on the test set
y_pred_rf = rf_model.predict(X)

# Evaluate the model
accuracy_rf = accuracy_score(y, y_pred_rf)
print(f"Random Forest Accuracy: {accuracy_rf}")


Random Forest Accuracy: 0.9937164117403886


In [179]:


from sklearn.metrics import f1_score

# Calculate the F1 score for XGBoost
f1_xgb = f1_score(y, y_pred_xgb)
print(f"XGBoost F1 Score: {f1_xgb}")

# Calculate the F1 score for Random Forest
f1_rf = f1_score(y, y_pred_rf)
print(f"Random Forest F1 Score: {f1_rf}")


XGBoost F1 Score: 0.9401216907764839
Random Forest F1 Score: 0.9953345610804174
